### ISSUE TITLE
Logglier should support Splunk Storm (take 2)

### ISSUE THREAD

**Issue by ampledata** [freeformz/logglier#20]
We're about to re-release the Storm API, so I'm picking up this issue again (see #16):

Now that Splunk Storm has a API for data input, it should be trivial to add support to Logglier.

Documentation for the Splunk Storm API is available at: 

* http://docs.splunk.com/Documentation/Storm/latest/User/UseStormsRESTAPI
* http://docs.splunk.com/Documentation/Storm/latest/User/Stormdatainputendpoint

Ruby examples of using the Splunk Storm API are available at: https://github.com/splunk/storm-examples

**Comment by freeformz** [comment]
Closing as this is OOOLLLLDDDD. Please file a new PR if there is still interest.
