### ISSUE TITLE
Is process id stored anywhere?

### ISSUE THREAD

**Issue by inspire22** [freeformz/logglier#32]
It seems pretty obvious, but if you have 4 processes on a host, it's hard to tell which one is generating which log entry.  Usually you'd log pid with this, but it doesn't seem to be in the template for what is sent to loggly.

I'm trying having hostname be "#{`hostname`}-#{$$}" for now, but still it seems to make sense to include pid...

**Comment by psquickitjayant** [comment]
@inspire22  did you use syslog udp or http?

**Comment by psquickitjayant** [comment]
Added process id in the log in #42

**Comment by freeformz** [comment]
Closing as this has been fixed AFAIK.
