### ISSUE TITLE
Use lograge with logglier

### ISSUE THREAD

**Issue by adrienbourgeois** [freeformz/logglier#38]
I cannot manage to make lograge work with logglier, is that even possible?

**Comment by iZoidberg** [comment]
Assuming you have configured lograge like described here in the readme. Put this code into your loggly initializer:
loggly = Logglier.new("your url")
Rails.configuration.lograge.logger.extend(ActiveSupport::Logger.broadcast(loggly))

**Comment by psquickitjayant** [comment]
@adrienbourgeois  any specific reason of using lograge in this case?

**Comment by mostlyjason** [comment]
Loggly supports lograge for syslog https://www.loggly.com/docs/rails-logs/. I guess this would give support for HTTP/S? I think most people use syslog though.

**Comment by freeformz** [comment]
Closing. Old. Please re-open if this is still an issue.
