### ISSUE TITLE
Constant TimeoutError is deprecated

### ISSUE THREAD

**Issue by TeamNautilus** [freeformz/logglier#46]
We have the last version of gem logglier (0.4.1) and with Ruby 2.2.3 it works correctly.
Now we have upgrade Ruby at version 2.3.0 and we get the warning:

gems/logglier-0.4.1/lib/logglier/client/http/sync.rb:11
warning: constant Logglier::Client::HTTP::NetHTTPProxy::TimeoutError is deprecated

Can we fix this warning?

Thankyou
Team Nautilus

**Comment by freeformz** [comment]
#47 "fixes" it, but I'm unsure which versions of Ruby raise which error (Timeout::Error vs TimeoutError), which will break older rubies using the gem, so I'm bunping the version to 0.5.0
