### ISSUE TITLE
Logging to default Rails log file as well as Loggly?

### ISSUE THREAD

**Issue by manuelmeurer** [freeformz/logglier#48]
I'm just setting up Loggly and one major question that I can't find the answer to on my account's Ruby setup page (https://myaccount.loggly.com/sources/setup/ruby), the [Loggly docs](https://www.loggly.com/docs/ruby-logs/) or the logglier README is how to keep logging to the default Rails log file AND log to Loggly on top of that.
It seems like [this](https://github.com/freeformz/logglier#with-rails-4) should do it but I'm not sure.

**Comment by katerynkas** [comment]
Have you figured this out? What version of rails are you using?

**Comment by manuelmeurer** [comment]
Nope. :( Rails 4.2

**Comment by freeformz** [comment]
I setup a default rails site and used the provided instructions and it works in that when I run `bin/rails server` I get logs to both STDOUT and to the destination (a local test service) specified in the loggly.rb file. However the logs were not formatted as `:json`.

Can you explain exactly what is not working?

**Comment by freeformz** [comment]
The messages aren't being formatted as json because rails isn't passing them in as a hash. https://github.com/freeformz/logglier/blob/fd709b186f0fa6e619b390c310520e6bd2d281ec/lib/logglier/client.rb#L63

**Comment by freeformz** [comment]
So I don't consider the fact that it's not json a bug atm, given that the rails logger serializes the logs to a string already.

**Comment by manuelmeurer** [comment]
Ok thanks, good to know! Might be worth adding this to the README or Loggly's account setup page for new users. I have since moved on to another logging service.
