### ISSUE TITLE
Issues connecting to loggly can affect a logglier consumer

### ISSUE THREAD

**Issue by dpiddy** [freeformz/logglier#9]
While testing other network/connection issue handling in fog, I set up iptables to reject all traffic to port 443. This made logglier raise `Errno::ECONNREFUSED` when loading my app since it of course couldn't open the https connection to loggly.

Would be nice if that were handled a bit better. In async/threaded mode, perhaps it could retry with a backoff. In sync mode maybe it could try connecting every time with a very short open timeout. Either way also attempting to queue events for delivery once the connection was established would be nice.

**Comment by freeformz** [comment]
Closing. Old. Please re-open if it's still an issue.
